[package]
name = "livedraw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svg = "0.12.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
isahc = "1.7.2"
