[package]
name = "art-template"
version = "0.1.0"
edition = "2021"

[dependencies]
livedraw = { path = "../livedraw-rust" }
clap = { version = "4.0.29", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
svg = "0.13"
rand = "0.8.5"
